
// Collection
const COLLECTION_REQUEST = 'COLLECTION_REQUEST';
const COLLECTION_SUCCESS = 'COLLECTION_SUCCESS';
const COLLECTION_FAILURE = 'COLLECTION_FAILURE';

// Collection by id 
const GET_COLLECTION_BY_ID_REQUEST = 'GET_COLLECTION_BY_ID_REQUEST';
const GET_COLLECTION_BY_ID_SUCCESS = 'GET_COLLECTION_BY_ID_SUCCESS';
const GET_COLLECTION_BY_ID_FAILURE = 'GET_COLLECTION_BY_ID_FAILURE';

// Collection by User id 
const GET_COLLECTION_BY_USER_ID_REQUEST = 'GET_COLLECTION_BY_USER_ID_REQUEST';
const GET_COLLECTION_BY_USER_ID_SUCCESS = 'GET_COLLECTION_BY_USER_ID_SUCCESS';
const GET_COLLECTION_BY_USER_ID_FAILURE = 'GET_COLLECTION_BY_USER_ID_FAILURE';

//Trending Collection
const TRENDING_COLLECTION_REQUEST = 'TRENDING_COLLECTION_REQUEST';
const TRENDING_COLLECTION_SUCCESS = 'TRENDING_COLLECTION_SUCCESS';
const TRENDING_COLLECTION_FAILURE = 'TRENDING_COLLECTION_FAILURE';

export {
    COLLECTION_REQUEST,
    COLLECTION_SUCCESS,
    COLLECTION_FAILURE,
    TRENDING_COLLECTION_REQUEST,
    TRENDING_COLLECTION_SUCCESS,
    TRENDING_COLLECTION_FAILURE,
    GET_COLLECTION_BY_ID_REQUEST,
    GET_COLLECTION_BY_ID_SUCCESS,
    GET_COLLECTION_BY_ID_FAILURE,
    GET_COLLECTION_BY_USER_ID_REQUEST,
    GET_COLLECTION_BY_USER_ID_SUCCESS,
    GET_COLLECTION_BY_USER_ID_FAILURE
};
