//Trading Reels
const TRADING_REELS_REQUEST = 'TRADING_REELS_REQUEST';
const TRADING_REELS_SUCCESS = 'TRADING_REELS_SUCCESS';
const TRADING_REELS_FAILURE = 'TRADING_REELS_FAILURE';

const EDIT_REELS_REQUEST = 'EDIT_REELS_REQUEST';
const EDIT_REELS_SUCCESS = 'EDIT_REELS_SUCCESS';
const EDIT_REELS_FAILURE = 'EDIT_REELS_FAILURE';

const GET_REELS_BY_USER_ID_REQUEST = 'GET_REELS_BY_USER_ID_REQUEST';
const GET_REELS_BY_USER_ID_SUCCESS = 'GET_REELS_BY_USER_ID_SUCCESS';
const GET_REELS_BY_USER_ID_FAILURE = 'GET_REELS_BY_USER_ID_FAILURE';

const GET_REEL_DETAILS_REQUEST = 'GET_REEL_DETAILS_REQUEST';
const GET_REEL_DETAILS_SUCCESS = 'GET_REEL_DETAILS_SUCCESS';
const GET_REEL_DETAILS_FAIL = 'GET_REEL_DETAILS_FAIL';

const GET_REELS_CATEGORY_REQUEST = 'GET_REELS_CATEGORY_REQUEST';
const GET_REELS_CATEGORY_SUCCESS = 'GET_REELS_CATEGORY_SUCCESS';
const GET_REELS_CATEGORY_FAILURE = 'GET_REELS_CATEGORY_FAILURE';

const DELETE_REEL_REQUEST = 'DELETE_REEL_REQUEST';
const DELETE_REEL_SUCCESS = 'DELETE_REEL_SUCCESS';
const DELETE_REEL_FAILURE = 'DELETE_REEL_FAILURE';

const GET_SAVED_REELS_REQUEST = 'GET_SAVED_REELS_REQUEST';
const GET_SAVED_REELS_SUCCESS = 'GET_SAVED_REELS_SUCCESS';
const GET_SAVED_REELS_FAILURE = 'GET_SAVED_REELS_FAILURE';

export {
    TRADING_REELS_REQUEST,
    TRADING_REELS_SUCCESS,
    TRADING_REELS_FAILURE,
    EDIT_REELS_REQUEST,
    EDIT_REELS_SUCCESS,
    EDIT_REELS_FAILURE,
    GET_REELS_BY_USER_ID_REQUEST,
    GET_REELS_BY_USER_ID_SUCCESS,
    GET_REELS_BY_USER_ID_FAILURE,
    GET_REEL_DETAILS_REQUEST,
    GET_REEL_DETAILS_SUCCESS,
    GET_REEL_DETAILS_FAIL,
    GET_REELS_CATEGORY_REQUEST,
    GET_REELS_CATEGORY_SUCCESS,
    GET_REELS_CATEGORY_FAILURE,
    GET_SAVED_REELS_REQUEST,
    GET_SAVED_REELS_SUCCESS,
    GET_SAVED_REELS_FAILURE,
    DELETE_REEL_REQUEST,
    DELETE_REEL_SUCCESS,
    DELETE_REEL_FAILURE
};
