
// Auctions
const AUCTION_REQUEST = 'AUCTION_REQUEST';
const AUCTION_SUCCESS = 'AUCTION_SUCCESS';
const AUCTION_FAILURE = 'AUCTION_FAILURE';

const TRENDING_AUCTION_REQUEST = 'TRENDING_AUCTION_REQUEST';
const TRENDING_AUCTION_SUCCESS = 'TRENDING_AUCTION_SUCCESS';
const TRENDING_AUCTION_FAILURE = 'TRENDING_AUCTION_FAILURE';

const GET_AUCTION_BY_ID_REQUEST = 'GET_AUCTION_BY_ID_REQUEST';
const GET_AUCTION_BY_ID_SUCCESS = 'GET_AUCTION_BY_ID_SUCCESS';
const GET_AUCTION_BY_ID_FAILURE = 'GET_AUCTION_BY_ID_FAILURE';

const ADD_AUCTION_REQUEST = 'ADD_AUCTION_REQUEST';
const ADD_AUCTION_SUCCESS = 'ADD_AUCTION_SUCCESS';
const ADD_AUCTION_FAILURE = 'ADD_AUCTION_FAILURE';

export {
    AUCTION_REQUEST,
    AUCTION_SUCCESS,
    AUCTION_FAILURE,
    GET_AUCTION_BY_ID_REQUEST,
    GET_AUCTION_BY_ID_SUCCESS,
    GET_AUCTION_BY_ID_FAILURE,
    ADD_AUCTION_REQUEST,
    ADD_AUCTION_SUCCESS,
    ADD_AUCTION_FAILURE,
    TRENDING_AUCTION_REQUEST,
    TRENDING_AUCTION_SUCCESS,
    TRENDING_AUCTION_FAILURE
};
