//Trading Reels
const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

const POST_COMMENTS_REQUEST = 'POST_COMMENTS_REQUEST';
const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
const POST_COMMENTS_FAILURE = 'POST_COMMENTS_FAILURE';

export {
  GET_COMMENTS_REQUEST,
  GET_COMMENTS_SUCCESS,
  GET_COMMENTS_FAILURE,
  POST_COMMENTS_REQUEST,
  POST_COMMENTS_SUCCESS,
  POST_COMMENTS_FAILURE,
};
