//Trading Reels
const GET_LIKE_REQUEST = 'GET_LIKE_REQUEST';
const GET_LIKE_SUCCESS = 'GET_LIKE_SUCCESS';
const GET_LIKE_FAILURE = 'GET_LIKE_FAILURE';

const SET_LIKE_REQUEST = 'SET_LIKE_REQUEST';
const SET_LIKE_SUCCESS = 'SET_LIKE_SUCCESS';
const SET_LIKE_FAILURE = 'SET_LIKE_FAILURE';

export {GET_LIKE_REQUEST, GET_LIKE_SUCCESS, GET_LIKE_FAILURE, SET_LIKE_REQUEST, SET_LIKE_SUCCESS, SET_LIKE_FAILURE};
