
// Login
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const USER_REQUEST = 'USER_REQUEST';
const USER_SUCCESS = 'USER_SUCCESS';
const USER_FAILURE = 'USER_FAILURE';

const USER_GET_FOLLOWING_REQUEST = 'USER_GET_FOLLOWING_REQUEST';
const USER_GET_FOLLOWING_SUCCESS = 'USER_GET_FOLLOWING_SUCCESS';
const USER_GET_FOLLOWING_FAILURE = 'USER_GET_FOLLOWING_FAILURE';

const USER_GET_FOLLOWERS_REQUEST = 'USER_GET_FOLLOWERS_REQUEST';
const USER_GET_FOLLOWERS_SUCCESS = 'USER_GET_FOLLOWERS_SUCCESS';
const USER_GET_FOLLOWERS_FAILURE = 'USER_GET_FOLLOWERS_FAILURE';

const USER_UPDATE_PREFERENCE_REQUEST = 'USER_UPDATE_PREFERENCE_REQUEST';
const USER_UPDATE_PREFERENCE_SUCCESS = 'USER_UPDATE_PREFERENCE_SUCCESS';
const USER_UPDATE_PREFERENCE_FAILURE = 'USER_UPDATE_PREFERENCE_FAILURE';

const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';

const USER_GET_BLOCK_REQUEST = 'USER_GET_BLOCK_REQUEST';
const USER_GET_BLOCK_SUCCESS = 'USER_GET_BLOCK_SUCCESS';
const USER_GET_BLOCK_FAILURE = 'USER_GET_BLOCK_FAILURE';

const USER_GET_RESTRICT_REQUEST = 'USER_GET_RESTRICT_REQUEST';
const USER_GET_RESTRICT_SUCCESS = 'USER_GET_RESTRICT_SUCCESS';
const USER_GET_RESTRICT_FAILURE = 'USER_GET_RESTRICT_FAILURE';

const USER_GET_MUTE_REQUEST = 'USER_GET_MUTE_REQUEST';
const USER_GET_MUTE_SUCCESS = 'USER_GET_MUTE_SUCCESS';
const USER_GET_MUTE_FAILURE = 'USER_GET_MUTE_FAILURE';

const USER_GET_CLOSED_REQUEST = 'USER_GET_CLOSED_REQUEST';
const USER_GET_CLOSED_SUCCESS = 'USER_GET_CLOSED_SUCCESS';
const USER_GET_CLOSED_FAILURE = 'USER_GET_CLOSED_FAILURE';

export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    USER_REQUEST,
    USER_SUCCESS,
    USER_FAILURE,
    USER_UPDATE_PREFERENCE_REQUEST,
    USER_UPDATE_PREFERENCE_SUCCESS,
    USER_UPDATE_PREFERENCE_FAILURE,
    USER_AUTH_REQUEST,
    USER_AUTH_SUCCESS,
    USER_AUTH_FAILURE,
    USER_GET_FOLLOWING_REQUEST,
    USER_GET_FOLLOWING_SUCCESS,
    USER_GET_FOLLOWING_FAILURE,
    USER_GET_BLOCK_REQUEST,
    USER_GET_BLOCK_SUCCESS,
    USER_GET_BLOCK_FAILURE,
    USER_GET_RESTRICT_REQUEST,
    USER_GET_RESTRICT_SUCCESS,
    USER_GET_RESTRICT_FAILURE,
    USER_GET_MUTE_REQUEST,
    USER_GET_MUTE_SUCCESS,
    USER_GET_MUTE_FAILURE,
    USER_GET_CLOSED_REQUEST,
    USER_GET_CLOSED_SUCCESS,
    USER_GET_CLOSED_FAILURE,
    USER_GET_FOLLOWERS_REQUEST,
    USER_GET_FOLLOWERS_SUCCESS,
    USER_GET_FOLLOWERS_FAILURE
};
