
// mapline
const NEAR_BY_USER_REQUEST = 'NEAR_BY_USER_REQUEST';
const NEAR_BY_USER_SUCCESS = 'NEAR_BY_USER_SUCCESS';
const NEAR_BY_USER_FAILURE = 'NEAR_BY_USER_FAILURE';

const GET_RECENT_ACTIVITY_REQUEST = 'GET_RECENT_ACTIVITY_REQUEST';
const GET_RECENT_ACTIVITY_SUCCESS = 'GET_RECENT_ACTIVITY_SUCCESS';
const GET_RECENT_ACTIVITY_FAILURE = 'GET_RECENT_ACTIVITY_FAILURE';

const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST';
const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';

export {
    NEAR_BY_USER_REQUEST,
    NEAR_BY_USER_SUCCESS,
    NEAR_BY_USER_FAILURE,
    GET_RECENT_ACTIVITY_REQUEST,
    GET_RECENT_ACTIVITY_SUCCESS,
    GET_RECENT_ACTIVITY_FAILURE,
    GET_PLACES_REQUEST,
    GET_PLACES_SUCCESS,
    GET_PLACES_FAILURE
};
