
// Search
const SEARCH_REQUEST = 'SEARCH_REQUEST';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
const SEARCH_FAILURE = 'SEARCH_FAILURE';

const RECENT_SEARCH_REQUEST = 'RECENT_SEARCH_REQUEST';
const RECENT_SEARCH_SUCCESS = 'RECENT_SEARCH_SUCCESS';
const RECENT_SEARCH_FAILURE = 'RECENT_SEARCH_FAILURE';

// const CLEAR_ALL_SEARCH_REQUEST = 'CLEAR_ALL_SEARCH_REQUEST';
// const CLEAR_ALL_SEARCH_SUCCESS = 'CLEAR_ALL_SEARCH_SUCCESS';
// const CLEAR_ALL_SEARCH_FAILURE = 'CLEAR_ALL_SEARCH_FAILURE';

// const ADD_RECENT_SEARCH_REQUEST = 'ADD_RECENT_SEARCH_REQUEST';
// const ADD_RECENT_SEARCH_SUCCESS = 'ADD_RECENT_SEARCH_SUCCESS';
// const ADD_RECENT_SEARCH_FAILURE = 'ADD_RECENT_SEARCH_FAILURE';

// const CLEAR_BY_ID_SEARCH_REQUEST = 'CLEAR_BY_ID_SEARCH_REQUEST';
// const CLEAR_BY_ID_SEARCH_SUCCESS = 'CLEAR_BY_ID_SEARCH_SUCCESS';
// const CLEAR_BY_ID_SEARCH_FAILURE = 'CLEAR_BY_ID_SEARCH_FAILURE';

export {
    SEARCH_REQUEST,
    SEARCH_SUCCESS,
    SEARCH_FAILURE,
    RECENT_SEARCH_REQUEST,
    RECENT_SEARCH_SUCCESS,
    RECENT_SEARCH_FAILURE,
    // CLEAR_ALL_SEARCH_REQUEST,
    // CLEAR_ALL_SEARCH_SUCCESS,
    // CLEAR_ALL_SEARCH_FAILURE,
    // ADD_RECENT_SEARCH_REQUEST,
    // ADD_RECENT_SEARCH_SUCCESS,
    // ADD_RECENT_SEARCH_FAILURE,
    // CLEAR_BY_ID_SEARCH_REQUEST,
    // CLEAR_BY_ID_SEARCH_SUCCESS,
    // CLEAR_BY_ID_SEARCH_FAILURE
};
