
// Post
const POST_REQUEST = 'POST_REQUEST';
const POST_SUCCESS = 'POST_SUCCESS';
const POST_FAILURE = 'POST_FAILURE';

const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';

const GET_POST_BY_USER_ID_REQUEST = 'GET_POST_BY_USER_ID_REQUEST';
const GET_POST_BY_USER_ID_SUCCESS = 'GET_POST_BY_USER_ID_SUCCESS';
const GET_POST_BY_USER_ID_FAILURE = 'GET_POST_BY_USER_ID_FAILURE';

const GET_SAVED_POST_REQUEST = 'GET_SAVED_POST_REQUEST';
const GET_SAVED_POST_SUCCESS = 'GET_SAVED_POST_SUCCESS';
const GET_SAVED_POST_FAILURE = 'GET_SAVED_POST_FAILURE';

const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
const GET_POST_BY_ID_FAILURE = 'GET_POST_BY_ID_FAILURE';

const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export {
    POST_REQUEST,
    POST_SUCCESS,
    POST_FAILURE,
    ADD_POST_REQUEST,
    ADD_POST_SUCCESS,
    ADD_POST_FAILURE,
    EDIT_POST_REQUEST,
    EDIT_POST_SUCCESS,
    EDIT_POST_FAILURE,
    GET_POST_BY_USER_ID_REQUEST,
    GET_POST_BY_USER_ID_SUCCESS,
    GET_POST_BY_USER_ID_FAILURE,
    GET_POST_BY_ID_REQUEST,
    GET_POST_BY_ID_SUCCESS,
    GET_POST_BY_ID_FAILURE,
    DELETE_POST_REQUEST,
    DELETE_POST_SUCCESS,
    DELETE_POST_FAILURE,
    GET_SAVED_POST_REQUEST,
    GET_SAVED_POST_SUCCESS,
    GET_SAVED_POST_FAILURE
};
