
// Registration
const MEDIA_REQUEST = 'SIGNUP_REQUEST';
const MEDIA_SUCCESS = 'SIGNUP_SUCCESS';
const MEDIA_FAILURE = 'SIGNUP_FAILURE';



export {
    MEDIA_REQUEST,
    MEDIA_SUCCESS,
    MEDIA_FAILURE,
};
