//Trading Reels
const GET_REPORT_CATEGORY_REQUEST = 'GET_REPORT_CATEGORY_REQUEST';
const GET_REPORT_CATEGORY_SUCCESS = 'GET_REPORT_CATEGORY_SUCCESS';
const GET_REPORT_CATEGORY_FAILURE = 'GET_REPORT_CATEGORY_FAILURE';

// const SET_REPORT_REQUEST = 'SET_REPORT_REQUEST';
// const SET_REPORT_SUCCESS = 'SET_REPORT_SUCCESS';
// const SET_REPORT_FAILURE = 'SET_REPORT_FAILURE';

export {
    GET_REPORT_CATEGORY_REQUEST,
    GET_REPORT_CATEGORY_SUCCESS,
    GET_REPORT_CATEGORY_FAILURE,
    // SET_REPORT_REQUEST,
    // SET_REPORT_SUCCESS,
    // SET_REPORT_FAILURE
};
