
// Registration
const ILLUSTRATION_REQUEST = 'ILLUSTRATION_REQUEST';
const ILLUSTRATION_SUCCESS = 'ILLUSTRATION_SUCCESS';
const ILLUSTRATION_FAILURE = 'ILLUSTRATION_FAILURE';

const ADD_ILLUSTRATION_REQUEST = 'ADD_ILLUSTRATION_REQUEST';
const ADD_ILLUSTRATION_SUCCESS = 'ADD_ILLUSTRATION_SUCCESS';
const ADD_ILLUSTRATION_FAILURE = 'ADD_ILLUSTRATION_FAILURE';

export {
    ILLUSTRATION_REQUEST,
    ILLUSTRATION_SUCCESS,
    ILLUSTRATION_FAILURE,
    ADD_ILLUSTRATION_REQUEST,
    ADD_ILLUSTRATION_SUCCESS,
    ADD_ILLUSTRATION_FAILURE,
};
