
// Nfts
const NFTS_REQUEST = 'NFTS_REQUEST';
const NFTS_SUCCESS = 'NFTS_SUCCESS';
const NFTS_FAILURE = 'NFTS_FAILURE';

const GET_NFTS_BY_ID_REQUEST = 'GET_NFTS_BY_ID_REQUEST';
const GET_NFTS_BY_ID_SUCCESS = 'GET_NFTS_BY_ID_SUCCESS';
const GET_NFTS_BY_ID_FAILURE = 'GET_NFTS_BY_ID_FAILURE';

const GET_NFTS_BY_USER_ID_REQUEST = 'GET_NFTS_BY_USER_ID_REQUEST';
const GET_NFTS_BY_USER_ID_SUCCESS = 'GET_NFTS_BY_USER_ID_SUCCESS';
const GET_NFTS_BY_USER_ID_FAILURE = 'GET_NFTS_BY_USER_ID_FAILURE';

const TRENDING_NFTS_REQUEST = 'TRENDING_NFTS_REQUEST';
const TRENDING_NFTS_SUCCESS = 'TRENDING_NFTS_SUCCESS';
const TRENDING_NFTS_FAILURE = 'TRENDING_NFTS_FAILURE';

const VIEW_NFTS_REQUEST = 'VIEW_NFTS_REQUEST';
const VIEW_NFTS_SUCCESS = 'VIEW_NFTS_SUCCESS';
const VIEW_NFTS_FAILURE = 'VIEW_NFTS_FAILURE';

const GET_SAVED_NFTS_REQUEST = 'GET_SAVED_NFTS_REQUEST';
const GET_SAVED_NFTS_SUCCESS = 'GET_SAVED_NFTS_SUCCESS';
const GET_SAVED_NFTS_FAILURE = 'GET_SAVED_NFTS_FAILURE';

export {
    NFTS_REQUEST,
    NFTS_SUCCESS,
    NFTS_FAILURE,
    GET_NFTS_BY_ID_REQUEST,
    GET_NFTS_BY_ID_SUCCESS,
    GET_NFTS_BY_ID_FAILURE,
    GET_NFTS_BY_USER_ID_REQUEST,
    GET_NFTS_BY_USER_ID_SUCCESS,
    GET_NFTS_BY_USER_ID_FAILURE,
    TRENDING_NFTS_REQUEST,
    TRENDING_NFTS_SUCCESS,
    TRENDING_NFTS_FAILURE,
    VIEW_NFTS_REQUEST,
    VIEW_NFTS_SUCCESS,
    VIEW_NFTS_FAILURE,
    GET_SAVED_NFTS_REQUEST,
    GET_SAVED_NFTS_SUCCESS,
    GET_SAVED_NFTS_FAILURE
};
