
// Registration
const FUTURE_VISITE_REQUEST = 'FUTURE_VISITE_REQUEST';
const FUTURE_VISITE_SUCCESS = 'FUTURE_VISITE_SUCCESS';
const FUTURE_VISITE_FAILURE = 'FUTURE_VISITE_FAILURE';

const ADD_FUTURE_VISITE_REQUEST = 'ADD_FUTURE_VISITE_REQUEST';
const ADD_FUTURE_VISITE_SUCCESS = 'ADD_FUTURE_VISITE_SUCCESS';
const ADD_FUTURE_VISITE_FAILURE = 'ADD_FUTURE_VISITE_FAILURE';

export {
    FUTURE_VISITE_REQUEST,
    FUTURE_VISITE_SUCCESS,
    FUTURE_VISITE_FAILURE,
    ADD_FUTURE_VISITE_REQUEST,
    ADD_FUTURE_VISITE_SUCCESS,
    ADD_FUTURE_VISITE_FAILURE,
};
