
// Bid

const ADD_BID_REQUEST = 'ADD_BID_REQUEST';
const ADD_BID_SUCCESS = 'ADD_BID_SUCCESS';
const ADD_BID_FAILURE = 'ADD_BID_FAILURE';

export {
    ADD_BID_REQUEST,
    ADD_BID_SUCCESS,
    ADD_BID_FAILURE,
};
