
// Registration
const STORIES_REQUEST = 'STORIES_REQUEST';
const STORIES_SUCCESS = 'STORIES_SUCCESS';
const STORIES_FAILURE = 'STORIES_FAILURE';

const ADD_STORIES_REQUEST = 'ADD_STORIES_REQUEST';
const ADD_STORIES_SUCCESS = 'ADD_STORIES_SUCCESS';
const ADD_STORIES_FAILURE = 'ADD_STORIES_FAILURE';

export {
    STORIES_REQUEST,
    STORIES_SUCCESS,
    STORIES_FAILURE,
    ADD_STORIES_REQUEST,
    ADD_STORIES_SUCCESS,
    ADD_STORIES_FAILURE,
};
